# 日志配置
[logger]
    #日志保存路径
    path        = "/tmp/log/easygoadmin"
    #日志级别
    level       = 0
    #标准输出流
    stdout      = true

# 数据库配置
[database]
    #主数据库
    master  = "root:@tcp(127.0.0.1:3306)/easygoadmin.iris.layui?charset=utf8&timeout=3s&parseTime=true&loc=Local"
    #从数据库 如果为空则表示只使用主数据
    slave = ""
    #sql调试开关
    debug = true
    #sql日志目录
    log = "/tmp/log/easygoadmin/sql"

# 系统配置
[easygoadmin]
    # 版本号
    version = "v2.1.0"
    # 调试模式
    debug = false
    # 图片域名
    image = "http://images.gin.layui"
    # 上传附件目录
    uploads = "D:\\RXThinkCMF\\uploads"